import { createClient } from '@/lib/supabase/client'

export interface SanitizationResult {
  sanitizedContent: string
  modifications: string[]
  riskScore: number
  originalLength: number
  sanitizedLength: number
}

// AI artifacts and metadata patterns to remove
const AI_ARTIFACTS = [
  // Model identification leakage
  /I (am|was|created|wrote) (this|the) (prompt|instruction)/gi,
  /(My|Our) name is [A-Z][a-z]+/gi,
  /Created by [A-Z][a-z]+/gi,
  /Generated by [A-Z][a-z]+/gi,
  /I'm (Claude|GPT|ChatGPT|Anthropic|OpenAI)/gi,
  /As an AI (assistant|model|language model)/gi,

  // System prompt leakage
  /\[SYSTEM\][\s\S]*?\[\/SYSTEM\]/gi,
  /<system>[\s\S]*?<\/system>/gi,
  /\[INST\][\s\S]*?\[\/INST\]/gi,
  /<\|im_start\|>[\s\S]*?<\|im_end\|>/gi,
  /Human:[\s\S]*?Assistant:/gi,

  // Training data references
  /According to my training (data|dataset)/gi,
  /Based on my training/gi,
  /My training (includes|covers|taught me)/gi,
  /I was trained (on|to|by)/gi,

  // Internal reasoning exposure
  /Let me think about this/gi,
  /I need to consider/gi,
  /Upon reflection/gi,
  /On second thought/gi,
  /Actually, let me reconsider/gi,

  // Meta-commentary about the task
  /This is an interesting (question|request|task)/gi,
  /I should note that/gi,
  /It's worth mentioning/gi,
  /I want to emphasize/gi,

  // Safety disclaimers that leak model behavior
  /I cannot and will not/gi,
  /I'm not able to/gi,
  /I don't have the ability to/gi,
  /I'm designed to/gi,

  // Confidence indicators that reveal AI uncertainty
  /I believe that/gi,
  /I think that/gi,
  /It seems to me/gi,
  /In my opinion/gi,
  /From my perspective/gi,

  // Direct model references
  /anthropic/gi,
  /openai/gi,
  /language model/gi,
  /ai assistant/gi,
  /artificial intelligence/gi
]

// Forbidden content patterns that should be redacted
const FORBIDDEN_PATTERNS = [
  // Personal information
  /\b\d{3}-\d{2}-\d{4}\b/g, // SSN
  /\b\d{4}\s?\d{4}\s?\d{4}\s?\d{4}\b/g, // Credit card
  /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, // Email
  /\b\d{3}-\d{3}-\d{4}\b/g, // Phone

  // API keys and tokens
  /sk-[a-zA-Z0-9]{48}/g, // OpenAI API keys
  /pk_live_[a-zA-Z0-9]{24}/g, // Stripe keys
  /Bearer\s+[a-zA-Z0-9_-]+/g, // Bearer tokens

  // Internal system references
  /localhost:\d+/g,
  /127\.0\.0\.1:\d+/g,
  /dev\.example\.com/g,
  /staging\.example\.com/g,

  // Potential prompt injection
  /ignore\s+previous\s+instructions/gi,
  /system\s+prompt/gi,
  /jailbreak/gi,
  /bypass\s+safety/gi,

  // Business sensitive information
  /internal\s+memo/gi,
  /confidential\s+document/gi,
  /company\s+secret/gi,
  /proprietary\s+information/gi
]

// Replacement strategies
const REPLACEMENTS = {
  '[REDACTED]': FORBIDDEN_PATTERNS,
  '[AI_ARTIFACT_REMOVED]': AI_ARTIFACTS.slice(0, 10), // Most obvious AI artifacts
  '': AI_ARTIFACTS.slice(10) // Less obvious ones - remove completely
}

export function sanitizeOutput(content: string): SanitizationResult {
  if (!content || content.trim().length === 0) {
    return {
      sanitizedContent: '',
      modifications: [],
      riskScore: 0,
      originalLength: 0,
      sanitizedLength: 0
    }
  }

  const originalLength = content.length
  let sanitized = content
  const modifications: string[] = []
  let riskScore = 0

  // Apply replacements
  for (const [replacement, patterns] of Object.entries(REPLACEMENTS)) {
    for (const pattern of patterns) {
      const matches = sanitized.match(pattern)
      if (matches) {
        sanitized = sanitized.replace(pattern, replacement)
        modifications.push(`Replaced ${matches.length} instance(s) of AI artifact/forbidden content`)

        // Increase risk score based on what was found
        if (replacement === '[REDACTED]') {
          riskScore += matches.length * 20
        } else if (replacement === '[AI_ARTIFACT_REMOVED]') {
          riskScore += matches.length * 10
        } else {
          riskScore += matches.length * 5
        }
      }
    }
  }

  // Additional sanitization steps
  sanitized = removeExcessiveWhitespace(sanitized)
  sanitized = removeEmptyLines(sanitized)
  sanitized = normalizeQuotes(sanitized)
  sanitized = removeTrailingPunctuation(sanitized)

  // Ensure no leaked system tokens remain
  sanitized = sanitized.replace(/<\|endoftext\|>/g, '')
  sanitized = sanitized.replace(/<pad>/g, '')
  sanitized = sanitized.replace(/<unk>/g, '')

  const sanitizedLength = sanitized.length
  riskScore = Math.min(riskScore, 100)

  return {
    sanitizedContent: sanitized.trim(),
    modifications,
    riskScore,
    originalLength,
    sanitizedLength
  }
}

function removeExcessiveWhitespace(content: string): string {
  return content
    .replace(/\s+/g, ' ') // Multiple spaces to single space
    .replace(/\n\s*\n\s*\n/g, '\n\n') // Multiple newlines to double newline
    .trim()
}

function removeEmptyLines(content: string): string {
  return content
    .split('\n')
    .filter(line => line.trim().length > 0)
    .join('\n')
}

function normalizeQuotes(content: string): string {
  return content
    .replace(/[""]/g, '"') // Smart quotes to regular quotes
    .replace(/['']/g, "'") // Smart apostrophes to regular apostrophes
}

function removeTrailingPunctuation(content: string): string {
  return content.replace(/[.!?;,]+\s*$/, '') // Remove trailing punctuation
}

// Advanced sanitization for specific content types
export function sanitizeMarkdown(markdown: string): SanitizationResult {
  const result = sanitizeOutput(markdown)

  // Additional markdown-specific sanitization
  let sanitized = result.sanitizedContent

  // Remove potentially dangerous markdown
  sanitized = sanitized.replace(/javascript:/gi, '') // Remove javascript: links
  sanitized = sanitized.replace(/data:/gi, '') // Remove data: URIs
  sanitized = sanitized.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '[SCRIPT_REMOVED]') // Remove script tags
  sanitized = sanitized.replace(/<iframe[^>]*>[\s\S]*?<\/iframe>/gi, '[IFRAME_REMOVED]') // Remove iframes

  // Clean up markdown formatting
  sanitized = sanitized.replace(/#{4,}/g, '###') // Limit heading levels
  sanitized = sanitized.replace(/\*{3,}/g, '**') // Limit emphasis

  if (sanitized !== result.sanitizedContent) {
    result.modifications.push('Applied markdown-specific sanitization')
    result.riskScore += 10
  }

  result.sanitizedContent = sanitized
  return result
}

export function sanitizeJSON(jsonString: string): SanitizationResult {
  try {
    const parsed = JSON.parse(jsonString)
    const sanitized = sanitizeObjectRecursively(parsed)
    const result = sanitizeOutput(JSON.stringify(sanitized, null, 2))
    result.modifications.push('Applied JSON-specific sanitization')
    return result
  } catch (error) {
    // If not valid JSON, treat as regular text
    return sanitizeOutput(jsonString)
  }
}

function sanitizeObjectRecursively(obj: any): any {
  if (typeof obj === 'string') {
    return sanitizeOutput(obj).sanitizedContent
  }

  if (Array.isArray(obj)) {
    return obj.map(sanitizeObjectRecursively)
  }

  if (obj && typeof obj === 'object') {
    const sanitized: any = {}
    for (const [key, value] of Object.entries(obj)) {
      // Skip potentially dangerous keys
      if (!['__proto__', 'constructor', 'prototype'].includes(key)) {
        sanitized[key] = sanitizeObjectRecursively(value)
      }
    }
    return sanitized
  }

  return obj
}

// Batch sanitization for multiple pieces of content
export async function sanitizeBatch(
  contents: string[],
  contentType: 'text' | 'markdown' | 'json' = 'text'
): Promise<SanitizationResult[]> {
  const results: SanitizationResult[] = []

  for (const content of contents) {
    let result: SanitizationResult

    switch (contentType) {
      case 'markdown':
        result = sanitizeMarkdown(content)
        break
      case 'json':
        result = sanitizeJSON(content)
        break
      default:
        result = sanitizeOutput(content)
        break
    }

    results.push(result)
  }

  // Log batch sanitization
  await logSanitizationBatch(results, contentType)

  return results
}

export async function logSanitization(
  result: SanitizationResult,
  contentType: string,
  userId?: string
): Promise<void> {
  try {
    const supabase = createClient()

    await supabase.from('sanitization_logs').insert({
      user_id: userId,
      content_type: contentType,
      original_length: result.originalLength,
      sanitized_length: result.sanitizedLength,
      modifications: result.modifications,
      risk_score: result.riskScore,
      created_at: new Date().toISOString()
    })
  } catch (error) {
    console.error('Error logging sanitization:', error)
  }
}

async function logSanitizationBatch(
  results: SanitizationResult[],
  contentType: string
): Promise<void> {
  try {
    const supabase = createClient()

    const totalRisk = results.reduce((sum, r) => sum + r.riskScore, 0)
    const averageRisk = results.length > 0 ? totalRisk / results.length : 0

    await supabase.from('sanitization_logs').insert({
      content_type: `batch_${contentType}`,
      batch_size: results.length,
      average_risk_score: averageRisk,
      total_modifications: results.reduce((sum, r) => sum + r.modifications.length, 0),
      created_at: new Date().toISOString()
    })
  } catch (error) {
    console.error('Error logging batch sanitization:', error)
  }
}

// Validate sanitized content meets safety requirements
export function validateSanitizedContent(result: SanitizationResult): {
  isValid: boolean
  issues: string[]
  requiresReview: boolean
} {
  const issues: string[] = []
  let requiresReview = false

  // Check if too much content was removed
  const reductionRatio = (result.originalLength - result.sanitizedLength) / result.originalLength
  if (reductionRatio > 0.5) {
    issues.push('excessive_content_removal')
    requiresReview = true
  }

  // Check risk score
  if (result.riskScore > 80) {
    issues.push('high_risk_content')
    requiresReview = true
  }

  // Check for remaining suspicious patterns
  const suspiciousPatterns = [
    /\[REDACTED\]/g,
    /\[AI_ARTIFACT_REMOVED\]/g,
    /ignore.*instructions/gi,
    /system.*prompt/gi
  ]

  for (const pattern of suspiciousPatterns) {
    if (pattern.test(result.sanitizedContent)) {
      issues.push('suspicious_patterns_remaining')
      requiresReview = true
    }
  }

  // Check for empty or too short content
  if (result.sanitizedContent.trim().length < 10) {
    issues.push('content_too_short')
  }

  return {
    isValid: issues.length === 0,
    issues,
    requiresReview
  }
}